// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package api

import "encoding/json"
import "fmt"

type AuctionRequestJson struct {
	// The type of agent to auction for
	AgentType []NexWorkload `json:"agent_type,omitempty"`

	// A unique identifier for the auction
	AuctionId string `json:"auction_id"`

	// A list of tags to associate with the node during auction. To be returned, node
	// must satisfy ALL tags
	Tags AuctionRequestJsonTags `json:"tags"`
}

// A list of tags to associate with the node during auction. To be returned, node
// must satisfy ALL tags
type AuctionRequestJsonTags struct {
	// Tags corresponds to the JSON schema field "tags".
	Tags map[string]string `json:"tags,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AuctionRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["auction_id"]; raw != nil && !ok {
		return fmt.Errorf("field auction_id in AuctionRequestJson: required")
	}
	if _, ok := raw["tags"]; raw != nil && !ok {
		return fmt.Errorf("field tags in AuctionRequestJson: required")
	}
	type Plain AuctionRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AuctionRequestJson(plain)
	return nil
}

type AuctionResponseJson struct {
	// A one-time identifier used to target deployments
	BidderId string `json:"bidder_id"`

	// The number of agents running and their workload counts
	Status AuctionResponseJsonStatus `json:"status"`

	// Tags corresponds to the JSON schema field "tags".
	Tags AuctionResponseJsonTags `json:"tags"`

	// The target nodes xkey
	TargetXkey string `json:"target_xkey"`

	// The uptime of the node
	Uptime string `json:"uptime"`

	// The version of the node
	Version string `json:"version"`
}

// The number of agents running and their workload counts
type AuctionResponseJsonStatus struct {
	// Status corresponds to the JSON schema field "status".
	Status map[string]int `json:"status,omitempty"`
}

type AuctionResponseJsonTags struct {
	// Tags corresponds to the JSON schema field "tags".
	Tags map[string]string `json:"tags,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AuctionResponseJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bidder_id"]; raw != nil && !ok {
		return fmt.Errorf("field bidder_id in AuctionResponseJson: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in AuctionResponseJson: required")
	}
	if _, ok := raw["tags"]; raw != nil && !ok {
		return fmt.Errorf("field tags in AuctionResponseJson: required")
	}
	if _, ok := raw["target_xkey"]; raw != nil && !ok {
		return fmt.Errorf("field target_xkey in AuctionResponseJson: required")
	}
	if _, ok := raw["uptime"]; raw != nil && !ok {
		return fmt.Errorf("field uptime in AuctionResponseJson: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in AuctionResponseJson: required")
	}
	type Plain AuctionResponseJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AuctionResponseJson(plain)
	return nil
}

type CloneWorkloadRequestJson struct {
	// NewTargetXkey corresponds to the JSON schema field "new_target_xkey".
	NewTargetXkey string `json:"new_target_xkey"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CloneWorkloadRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["new_target_xkey"]; raw != nil && !ok {
		return fmt.Errorf("field new_target_xkey in CloneWorkloadRequestJson: required")
	}
	type Plain CloneWorkloadRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CloneWorkloadRequestJson(plain)
	return nil
}

type CloneWorkloadResponseJson struct {
	// StartWorkloadRequest corresponds to the JSON schema field
	// "start_workload_request".
	StartWorkloadRequest *StartWorkloadRequestJson `json:"start_workload_request,omitempty"`
}

type NexWorkload string

type NodeInfoRequestJson struct {
	// Namespace of the node
	Namespace string `json:"namespace"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeInfoRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["namespace"]; raw != nil && !ok {
		return fmt.Errorf("field namespace in NodeInfoRequestJson: required")
	}
	type Plain NodeInfoRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NodeInfoRequestJson(plain)
	return nil
}

type NodeInfoResponseJson struct {
	// The unique identifier of the node
	NodeId string `json:"node_id"`

	// Tags corresponds to the JSON schema field "tags".
	Tags NodeInfoResponseJsonTags `json:"tags"`

	// The target nodes xkey
	TargetXkey string `json:"target_xkey"`

	// The uptime of the node
	Uptime string `json:"uptime"`

	// The version of the node
	Version string `json:"version"`

	// WorkloadSummaries corresponds to the JSON schema field "workload_summaries".
	WorkloadSummaries []WorkloadSummary `json:"workload_summaries"`
}

type NodeInfoResponseJsonTags struct {
	// Tags corresponds to the JSON schema field "tags".
	Tags map[string]string `json:"tags,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeInfoResponseJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node_id"]; raw != nil && !ok {
		return fmt.Errorf("field node_id in NodeInfoResponseJson: required")
	}
	if _, ok := raw["tags"]; raw != nil && !ok {
		return fmt.Errorf("field tags in NodeInfoResponseJson: required")
	}
	if _, ok := raw["target_xkey"]; raw != nil && !ok {
		return fmt.Errorf("field target_xkey in NodeInfoResponseJson: required")
	}
	if _, ok := raw["uptime"]; raw != nil && !ok {
		return fmt.Errorf("field uptime in NodeInfoResponseJson: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in NodeInfoResponseJson: required")
	}
	if _, ok := raw["workload_summaries"]; raw != nil && !ok {
		return fmt.Errorf("field workload_summaries in NodeInfoResponseJson: required")
	}
	type Plain NodeInfoResponseJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NodeInfoResponseJson(plain)
	return nil
}

type NodePingResponseJson struct {
	// The unique identifier of the node
	NodeId string `json:"node_id"`

	// The number of agents running with workload count
	RunningAgents NodePingResponseJsonRunningAgents `json:"running_agents"`

	// Tags corresponds to the JSON schema field "tags".
	Tags NodePingResponseJsonTags `json:"tags"`

	// The target nodes xkey
	TargetXkey string `json:"target_xkey"`

	// The uptime of the node
	Uptime string `json:"uptime"`

	// The version of the node
	Version string `json:"version"`
}

// The number of agents running with workload count
type NodePingResponseJsonRunningAgents struct {
	// Status corresponds to the JSON schema field "status".
	Status map[string]int `json:"status,omitempty"`
}

type NodePingResponseJsonTags struct {
	// Tags corresponds to the JSON schema field "tags".
	Tags map[string]string `json:"tags,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodePingResponseJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node_id"]; raw != nil && !ok {
		return fmt.Errorf("field node_id in NodePingResponseJson: required")
	}
	if _, ok := raw["running_agents"]; raw != nil && !ok {
		return fmt.Errorf("field running_agents in NodePingResponseJson: required")
	}
	if _, ok := raw["tags"]; raw != nil && !ok {
		return fmt.Errorf("field tags in NodePingResponseJson: required")
	}
	if _, ok := raw["target_xkey"]; raw != nil && !ok {
		return fmt.Errorf("field target_xkey in NodePingResponseJson: required")
	}
	if _, ok := raw["uptime"]; raw != nil && !ok {
		return fmt.Errorf("field uptime in NodePingResponseJson: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in NodePingResponseJson: required")
	}
	type Plain NodePingResponseJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NodePingResponseJson(plain)
	return nil
}

type WorkloadSummary struct {
	// The unique identifier of the workload
	Id string `json:"id"`

	// The name of the workload
	Name string `json:"name"`

	// The runtime of the workload
	Runtime string `json:"runtime"`

	// The start time of the workload
	StartTime string `json:"start_time"`

	// The runtype/lifecycle of the workload
	WorkloadRuntype string `json:"workload_runtype"`

	// The state of the workload
	WorkloadState string `json:"workload_state"`

	// The type of the workload
	WorkloadType string `json:"workload_type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkloadSummary) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in WorkloadSummary: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in WorkloadSummary: required")
	}
	if _, ok := raw["runtime"]; raw != nil && !ok {
		return fmt.Errorf("field runtime in WorkloadSummary: required")
	}
	if _, ok := raw["start_time"]; raw != nil && !ok {
		return fmt.Errorf("field start_time in WorkloadSummary: required")
	}
	if _, ok := raw["workload_runtype"]; raw != nil && !ok {
		return fmt.Errorf("field workload_runtype in WorkloadSummary: required")
	}
	if _, ok := raw["workload_state"]; raw != nil && !ok {
		return fmt.Errorf("field workload_state in WorkloadSummary: required")
	}
	if _, ok := raw["workload_type"]; raw != nil && !ok {
		return fmt.Errorf("field workload_type in WorkloadSummary: required")
	}
	type Plain WorkloadSummary
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = WorkloadSummary(plain)
	return nil
}
