// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package native

import "encoding/json"
import "fmt"

type StartRequest struct {
	// Arguments to be passed to the binary
	Argv []string `json:"argv,omitempty"`

	// A description of the workload
	Description *string `json:"description,omitempty"`

	// The base64-encoded byte array of the encrypted environment with public key of
	// encryptor
	Environment StartRequestEnvironment `json:"environment,omitempty"`

	// The URI of the workload
	Uri string `json:"uri"`
}

// The base64-encoded byte array of the encrypted environment with public key of
// encryptor
type StartRequestEnvironment map[string]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *StartRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["uri"]; raw != nil && !ok {
		return fmt.Errorf("field uri in StartRequest: required")
	}
	type Plain StartRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StartRequest(plain)
	return nil
}
