// Message definitions for communciation with and between agent actors
// This is NOT the API definition for host services or the internal NATS server agent comms
// protocol.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: agents.proto

package actorproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Probably not going to be used. Placeholder to get at least one field until we
// fill out the other structs
type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Sent by the control API actor to an agent actor to request a workload be started
type StartWorkload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartWorkload) Reset() {
	*x = StartWorkload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkload) ProtoMessage() {}

func (x *StartWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkload.ProtoReflect.Descriptor instead.
func (*StartWorkload) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{1}
}

// Reply from the agent actor containing the results of the attempt to start a workload
type WorkloadStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WorkloadStarted) Reset() {
	*x = WorkloadStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStarted) ProtoMessage() {}

func (x *WorkloadStarted) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStarted.ProtoReflect.Descriptor instead.
func (*WorkloadStarted) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{2}
}

// Request sent by the control API actor to an agent actor asking to stop a workload
type StopWorkload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopWorkload) Reset() {
	*x = StopWorkload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkload) ProtoMessage() {}

func (x *StopWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkload.ProtoReflect.Descriptor instead.
func (*StopWorkload) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{3}
}

// Response from the agent actor indicating the results of the workload stop attempt
type WorkloadStopped struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WorkloadStopped) Reset() {
	*x = WorkloadStopped{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadStopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStopped) ProtoMessage() {}

func (x *WorkloadStopped) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStopped.ProtoReflect.Descriptor instead.
func (*WorkloadStopped) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{4}
}

// Asks the target agent for a list of all if its known, running workloads
type QueryWorkloads struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryWorkloads) Reset() {
	*x = QueryWorkloads{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryWorkloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkloads) ProtoMessage() {}

func (x *QueryWorkloads) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkloads.ProtoReflect.Descriptor instead.
func (*QueryWorkloads) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{5}
}

type WorkloadListing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workloads []*WorkloadSummary `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
}

func (x *WorkloadListing) Reset() {
	*x = WorkloadListing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadListing) ProtoMessage() {}

func (x *WorkloadListing) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadListing.ProtoReflect.Descriptor instead.
func (*WorkloadListing) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{6}
}

func (x *WorkloadListing) GetWorkloads() []*WorkloadSummary {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type WorkloadSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
}

func (x *WorkloadSummary) Reset() {
	*x = WorkloadSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSummary) ProtoMessage() {}

func (x *WorkloadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSummary.ProtoReflect.Descriptor instead.
func (*WorkloadSummary) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{7}
}

func (x *WorkloadSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadSummary) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// Request made by the actor system and/or control API asking the agent to stop. Note
// that the direct start agent will ignore this
type Halt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Halt) Reset() {
	*x = Halt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Halt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Halt) ProtoMessage() {}

func (x *Halt) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Halt.ProtoReflect.Descriptor instead.
func (*Halt) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{8}
}

var File_agents_proto protoreflect.FileDescriptor

var file_agents_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x11, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53,
	0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x57,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x22, 0x48, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x35, 0x0a, 0x09, 0x77,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x73, 0x22, 0x60, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x06, 0x0a, 0x04, 0x48, 0x61, 0x6c, 0x74, 0x42, 0x35, 0x5a, 0x33,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6e, 0x61, 0x64,
	0x69, 0x61, 0x2d, 0x69, 0x6f, 0x2f, 0x6e, 0x65, 0x78, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x70, 0x62, 0x3b, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agents_proto_rawDescOnce sync.Once
	file_agents_proto_rawDescData = file_agents_proto_rawDesc
)

func file_agents_proto_rawDescGZIP() []byte {
	file_agents_proto_rawDescOnce.Do(func() {
		file_agents_proto_rawDescData = protoimpl.X.CompressGZIP(file_agents_proto_rawDescData)
	})
	return file_agents_proto_rawDescData
}

var file_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_agents_proto_goTypes = []interface{}{
	(*Ping)(nil),                  // 0: agents.Ping
	(*StartWorkload)(nil),         // 1: agents.StartWorkload
	(*WorkloadStarted)(nil),       // 2: agents.WorkloadStarted
	(*StopWorkload)(nil),          // 3: agents.StopWorkload
	(*WorkloadStopped)(nil),       // 4: agents.WorkloadStopped
	(*QueryWorkloads)(nil),        // 5: agents.QueryWorkloads
	(*WorkloadListing)(nil),       // 6: agents.WorkloadListing
	(*WorkloadSummary)(nil),       // 7: agents.WorkloadSummary
	(*Halt)(nil),                  // 8: agents.Halt
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_agents_proto_depIdxs = []int32{
	7, // 0: agents.WorkloadListing.workloads:type_name -> agents.WorkloadSummary
	9, // 1: agents.WorkloadSummary.started_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agents_proto_init() }
func file_agents_proto_init() {
	if File_agents_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartWorkload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopWorkload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadStopped); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryWorkloads); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadListing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Halt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agents_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agents_proto_goTypes,
		DependencyIndexes: file_agents_proto_depIdxs,
		MessageInfos:      file_agents_proto_msgTypes,
	}.Build()
	File_agents_proto = out.File
	file_agents_proto_rawDesc = nil
	file_agents_proto_goTypes = nil
	file_agents_proto_depIdxs = nil
}
