{
 "title": "NATs Execution Engine (NEX)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "nex_workload_count by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nex_workload_count{namespace!=\"\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "nex_deployed_bytes_count by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nex_deployed_bytes_count{namespace!=\"\"}",
     "legendFormat": "{{namespace}}"
    },
    {}
   ]
  },
  {
   "title": "nex_deployed_bytes_count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nex_deployed_bytes_count{namespace=\"\"}"
    }
   ]
  },
  {
   "title": "nex_workload_count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nex_workload_count{namespace=\"\"}"
    }
   ]
  },
  {
   "title": "nex_total_memory_allocation_mib_count by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "nex_total_memory_allocation_mib_count{namespace!=\"\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "nex_total_vcpu_allocation_count by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nex_total_vcpu_allocation_count{namespace!=\"\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "nex_total_memory_allocation_mib_count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nex_total_memory_allocation_mib_count{namespace=\"\"}"
    }
   ]
  },
  {
   "title": "nex_total_vcpu_allocation_count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nex_total_vcpu_allocation_count{namespace=\"\"}"
    }
   ]
  }
 ]
}