// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

import "encoding/json"
import "fmt"

type AuctionRequest struct {
	// The type of agent to use for the auction
	AgentType string `json:"agent_type"`

	// A unique identifier for the auction
	AuctionId string `json:"auction_id"`

	// A map of tags to use for the auction
	Tags NodeTags `json:"tags"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AuctionRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["agent_type"]; raw != nil && !ok {
		return fmt.Errorf("field agent_type in AuctionRequest: required")
	}
	if _, ok := raw["auction_id"]; raw != nil && !ok {
		return fmt.Errorf("field auction_id in AuctionRequest: required")
	}
	if _, ok := raw["tags"]; raw != nil && !ok {
		return fmt.Errorf("field tags in AuctionRequest: required")
	}
	type Plain AuctionRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = AuctionRequest(plain)
	return nil
}

type AuctionResponse struct {
	// A one-time identifier used to target deployments
	BidderId string `json:"bidder_id"`

	// Schema for the start request
	StartRequestSchema string `json:"start_request_schema"`

	// Supported lifecycle types
	SupportedLifecycles []WorkloadLifecycle `json:"supported_lifecycles"`

	// Key used for encrypting parts of start request
	Xkey string `json:"xkey"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AuctionResponse) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["bidder_id"]; raw != nil && !ok {
		return fmt.Errorf("field bidder_id in AuctionResponse: required")
	}
	if _, ok := raw["start_request_schema"]; raw != nil && !ok {
		return fmt.Errorf("field start_request_schema in AuctionResponse: required")
	}
	if _, ok := raw["supported_lifecycles"]; raw != nil && !ok {
		return fmt.Errorf("field supported_lifecycles in AuctionResponse: required")
	}
	if _, ok := raw["xkey"]; raw != nil && !ok {
		return fmt.Errorf("field xkey in AuctionResponse: required")
	}
	type Plain AuctionResponse
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = AuctionResponse(plain)
	return nil
}

type CloneWorkloadRequest struct {
	// Namespace corresponds to the JSON schema field "namespace".
	Namespace string `json:"namespace"`

	// NewTargetXkey corresponds to the JSON schema field "new_target_xkey".
	NewTargetXkey string `json:"new_target_xkey"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CloneWorkloadRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["namespace"]; raw != nil && !ok {
		return fmt.Errorf("field namespace in CloneWorkloadRequest: required")
	}
	if _, ok := raw["new_target_xkey"]; raw != nil && !ok {
		return fmt.Errorf("field new_target_xkey in CloneWorkloadRequest: required")
	}
	type Plain CloneWorkloadRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CloneWorkloadRequest(plain)
	return nil
}

type CloneWorkloadResponse struct {
	// StartWorkloadRequest corresponds to the JSON schema field
	// "start_workload_request".
	StartWorkloadRequest *StartWorkloadRequest `json:"start_workload_request,omitempty"`
}

type NodeInfoRequest map[string]interface{}

type NodeInfoResponse struct {
	// AgentSummaries corresponds to the JSON schema field "agent_summaries".
	AgentSummaries AgentSummaries `json:"agent_summaries,omitempty"`

	// The public nkey of the node
	NodeId string `json:"node_id"`

	// Placement tags associated with node
	Tags NodeTags `json:"tags"`

	// The uptime of the node
	Uptime string `json:"uptime"`

	// The version of the node
	Version string `json:"version"`

	// The public xkey of node
	Xkey string `json:"xkey"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodeInfoResponse) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["node_id"]; raw != nil && !ok {
		return fmt.Errorf("field node_id in NodeInfoResponse: required")
	}
	if _, ok := raw["tags"]; raw != nil && !ok {
		return fmt.Errorf("field tags in NodeInfoResponse: required")
	}
	if _, ok := raw["uptime"]; raw != nil && !ok {
		return fmt.Errorf("field uptime in NodeInfoResponse: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in NodeInfoResponse: required")
	}
	if _, ok := raw["xkey"]; raw != nil && !ok {
		return fmt.Errorf("field xkey in NodeInfoResponse: required")
	}
	type Plain NodeInfoResponse
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NodeInfoResponse(plain)
	return nil
}

type NodePingRequest struct {
	// Filter corresponds to the JSON schema field "filter".
	Filter NodePingRequestFilter `json:"filter"`
}

type NodePingRequestFilter map[string]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodePingRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["filter"]; raw != nil && !ok {
		return fmt.Errorf("field filter in NodePingRequest: required")
	}
	type Plain NodePingRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NodePingRequest(plain)
	return nil
}

type NodePingResponse struct {
	// The number of agents running on the node
	AgentCount int `json:"agent_count"`

	// The unique identifier of the node
	NodeId string `json:"node_id"`

	// The state of the node
	State NodeState `json:"state"`

	// Placement tags associated with node
	Tags NodeTags `json:"tags"`

	// The uptime of the node
	Uptime string `json:"uptime"`

	// The version of the node
	Version string `json:"version"`

	// The target nodes xkey
	Xkey string `json:"xkey"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NodePingResponse) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["agent_count"]; raw != nil && !ok {
		return fmt.Errorf("field agent_count in NodePingResponse: required")
	}
	if _, ok := raw["node_id"]; raw != nil && !ok {
		return fmt.Errorf("field node_id in NodePingResponse: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in NodePingResponse: required")
	}
	if _, ok := raw["tags"]; raw != nil && !ok {
		return fmt.Errorf("field tags in NodePingResponse: required")
	}
	if _, ok := raw["uptime"]; raw != nil && !ok {
		return fmt.Errorf("field uptime in NodePingResponse: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in NodePingResponse: required")
	}
	if _, ok := raw["xkey"]; raw != nil && !ok {
		return fmt.Errorf("field xkey in NodePingResponse: required")
	}
	type Plain NodePingResponse
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NodePingResponse(plain)
	return nil
}
