// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

import "encoding/json"
import "fmt"
import "reflect"

type AgentLameduckSetEvent struct {
	// Indicates if the lameduck setting was successful
	Success bool `json:"success"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentLameduckSetEvent) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["success"]; raw != nil && !ok {
		return fmt.Errorf("field success in AgentLameduckSetEvent: required")
	}
	type Plain AgentLameduckSetEvent
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = AgentLameduckSetEvent(plain)
	return nil
}

type AgentStartedEvent struct {
	// The unique identifier of the nex agent
	Id string `json:"id"`

	// The name of the agent
	Name string `json:"name"`

	// The public xkey of the agent
	PublicXkey string `json:"public_xkey"`

	// The type of the agent
	Type AgentStartedEventType `json:"type"`
}

type AgentStartedEventType string

const AgentStartedEventTypeEmbedded AgentStartedEventType = "embedded"
const AgentStartedEventTypeLocal AgentStartedEventType = "local"
const AgentStartedEventTypeRemote AgentStartedEventType = "remote"

var enumValues_AgentStartedEventType = []interface{}{
	"embedded",
	"local",
	"remote",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentStartedEventType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AgentStartedEventType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AgentStartedEventType, v)
	}
	*j = AgentStartedEventType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentStartedEvent) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in AgentStartedEvent: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in AgentStartedEvent: required")
	}
	if _, ok := raw["public_xkey"]; raw != nil && !ok {
		return fmt.Errorf("field public_xkey in AgentStartedEvent: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in AgentStartedEvent: required")
	}
	type Plain AgentStartedEvent
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = AgentStartedEvent(plain)
	return nil
}

type NexNodeStartedEvent struct {
	// The unique identifier of the nex node
	Id string `json:"id"`

	// The name of the nex node
	Name string `json:"name"`

	// Nexus the nex node belongs to
	Nexus string `json:"nexus"`

	// Placement tags associated with the nex node
	Tags NodeTags `json:"tags"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NexNodeStartedEvent) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in NexNodeStartedEvent: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in NexNodeStartedEvent: required")
	}
	if _, ok := raw["nexus"]; raw != nil && !ok {
		return fmt.Errorf("field nexus in NexNodeStartedEvent: required")
	}
	if _, ok := raw["tags"]; raw != nil && !ok {
		return fmt.Errorf("field tags in NexNodeStartedEvent: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in NexNodeStartedEvent: required")
	}
	type Plain NexNodeStartedEvent
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NexNodeStartedEvent(plain)
	return nil
}

type WorkloadStartedEvent struct {
	// The unique identifier of the workload
	Id string `json:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkloadStartedEvent) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in WorkloadStartedEvent: required")
	}
	type Plain WorkloadStartedEvent
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = WorkloadStartedEvent(plain)
	return nil
}

type WorkloadStoppedEvent struct {
	// The unique identifier of the workload
	Id string `json:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkloadStoppedEvent) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in WorkloadStoppedEvent: required")
	}
	type Plain WorkloadStoppedEvent
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = WorkloadStoppedEvent(plain)
	return nil
}
